services:

  wiremock:
    image: wiremock/wiremock:3.13.0
    ports:
      - '8081:8080'
    volumes:
      - ./src/gatling/resources/wiremock/mappings:/home/wiremock/mappings
      - ./src/gatling/resources/wiremock/responses:/home/wiremock/__files
    environment:
      WIREMOCK_OPTIONS: '--global-response-templating'
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/__admin/version"]
      interval: 2s
      timeout: 60s
      retries: 30

  artifactory-badge:
    image: devatherock/artifactory-badge:${DOCKER_TAG:-latest}
    container_name: artifactory-badge-perf
    depends_on:
      - wiremock
    ports:
      - '8080:8080'
    volumes:
      - ./src/gatling/resources/application-perf.yml:/config/application.yml
    environment:
      MICRONAUT_CONFIG_FILES: '/config/application.yml'

  health:
    image: alpine:3.21.3
    depends_on:
      - artifactory-badge
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://artifactory-badge:8080/health"]
      interval: 2s
      timeout: 60s
      retries: 30
    command: |
      sh -c '
        wget -q -O - http://artifactory-badge:8080/health
        sleep 120
      '
